### PR TITLE
resource/ovirt_vm: Improve the implementations and fix bugs

### PR DESCRIPTION
**Pull request by imjoey**
Partially Fixes issue #32. 

Changes proposed in this pull request:

* Add `attached_disk` field in `ovirt_vm` resource
> Current `ovirt_disk_attachment` resource has lots of limitations. For example, the add/update/delete a disk attachment typically requires changing relevant VM lifecycle status, but it's confusing that the lifecycle operation is done by `ovirt_disk_attachment` Resource. The old  `ovirt_disk_attachment` Resource may mark as `deprecated` in the near future.

* Wait until the VM is up at the end of VM creation
> Thanks to the newly added `attached_disk` field. 😄 

* Add `vnic` field with the type of `schema.TypeSet`, to represent the vnic configurations for VM
* Rename `network_interace` field to `nic_configuration`, to represent the network initialization configurations
* Add `initialization` field and get `authorized_ssh_key` and `nic_configuration` moved in
> The above three changes are to completely distinguish the `vnic` settings from the `initialization network configurations` which are both optional attribute that be able to configured respectively. Meanwhile set `initialization` as independent field representing the [VM initialization structure](
http://ovirt.github.io/ovirt-engine-api-model/master/#types/initialization).

* Add `cluster_id` field to replace the `cluster` (which is the cluster name)

* Set all fields to `ForceNew: true` to support Terraform update operations
> This is a temporary way and will be fixed soon.

* Complete the `resourceOvirtVMRead` function

* Add retry mechanism in deleting the disk

* Add an acceptance test of common case  for `ovirt_vm` resource

* Update main.tf

Output from the acceptance test: (Updated after #42 got merged)
```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtVM_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtVM_ -timeout 180m
=== RUN   TestAccOvirtVM_basic
--- PASS: TestAccOvirtVM_basic (98.66s)
PASS
ok  	github.com/EMSL-MSC/terraform-provider-ovirt/ovirt	98.690s
```

### CODE REVIEW

**Comment by imjoey** [comment]
hi @bmanojlovic , this pull request has significant changes that has broken some existing Terraform Configurations. So could you please take a look to confirm that if these changes are appropriate. Any discussions are appreciated. Thanks.

**Comment by bmanojlovic** [comment]
did not had enough time to test today, will look into it tomorrow.

**Comment by imjoey** [comment]
@bmanojlovic  no need to test locally since the acceptance test has passed. Just see it as a proposal for new schema of `ovirt_vm` resource. 😄

**Comment by MichaelMalike** [comment]
@imjoey Good! I think the logical relation is more clear and more like oVirt style now.

**Comment by imjoey** [comment]
I might get it merged first. If any confusions or objections, we could discuss here then.

**Comment by bmanojlovic** [comment]
back to initial problem with conflict  :-) 

```
terraform apply -auto-approve
data.ovirt_datacenters.DC: Refreshing state...
data.ovirt_clusters.MYCluster: Refreshing state...
data.ovirt_networks.net02: Refreshing state...
data.ovirt_networks.net01: Refreshing state...
data.ovirt_storagedomains.sd: Refreshing state...
ovirt_disk.additional_disk: Creating...
  alias:             "" => "my_vm_disk_01"
  format:            "" => "cow"
  name:              "" => "my_vm_disk_01"
  size:              "" => "10737418240"
  sparse:            "" => "true"
  storage_domain_id: "" => "5f0e59a0-8ddf-11e8-808c-74d02b9d5600"
ovirt_disk.additional_disk: Creation complete after 1s (ID: 6933d9be-3103-4cb6-bc54-cd5578f0717e)
ovirt_vm.vm01: Creating...
  attached_disk.#:                                 "" => "1"
  attached_disk.4134799119.active:                 "" => "true"
  attached_disk.4134799119.bootable:               "" => "true"
  attached_disk.4134799119.disk_id:                "" => "6933d9be-3103-4cb6-bc54-cd5578f0717e"
  attached_disk.4134799119.interface:              "" => "virtio"
  attached_disk.4134799119.logical_name:           "" => ""
  attached_disk.4134799119.pass_discard:           "" => ""
  attached_disk.4134799119.read_only:              "" => "false"
  attached_disk.4134799119.use_scsi_reservation:   "" => "false"
  cluster_id:                                      "" => "5558027a-6077-4922-b4f0-4a0bab78d238"
  cores:                                           "" => "1"
  initialization.#:                                "" => "1"
  initialization.0.authorized_ssh_key:             "" => "ssh-rsa AAAKEY\n"
  initialization.0.nic_configuration.#:            "" => "2"
  initialization.0.nic_configuration.0.address:    "" => "10.11.16.250"
  initialization.0.nic_configuration.0.boot_proto: "" => "static"
  initialization.0.nic_configuration.0.gateway:    "" => "10.11.17.254"
  initialization.0.nic_configuration.0.label:      "" => "eth0"
  initialization.0.nic_configuration.0.netmask:    "" => "255.255.254.0"
  initialization.0.nic_configuration.0.on_boot:    "" => "true"
  initialization.0.nic_configuration.1.address:    "" => "10.22.16.231"
  initialization.0.nic_configuration.1.boot_proto: "" => "static"
  initialization.0.nic_configuration.1.gateway:    "" => "10.22.16.254"
  initialization.0.nic_configuration.1.label:      "" => "eth1"
  initialization.0.nic_configuration.1.netmask:    "" => "255.255.254.0"
  initialization.0.nic_configuration.1.on_boot:    "" => "true"
  name:                                            "" => "my_vm_1"
  sockets:                                         "" => "1"
  template:                                        "" => "centos7_20180720"
  threads:                                         "" => "1"
ovirt_vm.vm01: Still creating... (10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* ovirt_vm.vm01: 1 error(s) occurred:

* ovirt_vm.vm01: Fault reason is "Operation Failed". Fault detail is "[Cannot attach Virtual Disk because the VM is in Image Locked status.]". HTTP response code is "409". HTTP response message is "409 Conflict".

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

**Comment by imjoey** [comment]
@bmanojlovic my apologize, fixed in #43 .

**Pull request merged**
